In [108]:
import pandas as pd

df = pd.read_csv("2022서울시교통사고현황-데이터셋.csv",encoding = 'utf-8')

In [109]:
df.columns

Index(['행정동', 'total_population', 'street parking', 'senior_ratio',
       '사고유형 - 대분류', '사고유형 - 소분류', '법규위반', '도로형태 - 대분류', '도로형태 - 소분류',
       '가해운전자 차종', '가해운전자 연령대', 'ECLO'],
      dtype='object')

In [135]:
df1 = df[df["사고유형 - 대분류"] == "차량단독 "]  # 차량단독
df2 = df[df["사고유형 - 대분류"] == "차대차 "]  # 차대차
df3 = df[df["사고유형 - 대분류"] == "차대사람 "]  # 차대사람

In [134]:
df3

,행정동,total_population,street parking,senior_ratio,사고유형 - 대분류,사고유형 - 소분류,법규위반,도로형태 - 대분류,도로형태 - 소분류,가해운전자 차종,가해운전자 연령대,ECLO
0,신천동,37899,115,0.169741,차대사람,횡단중,보행자보호의무위반,단일로,기타,승용,60대,10
3,역삼동,71999,954,0.108182,차대사람,기타,안전운전불이행,교차로,교차로안,승용,60대,5
18,미아동,128883,1110,0.219602,차대사람,길가장자리구역통행중,안전운전불이행,교차로,교차로안,승용,30대,3
19,상도동,80214,520,0.189493,차대사람,차도통행중,안전운전불이행,단일로,기타,승용,40대,3
23,대조동,27841,193,0.195216,차대사람,횡단중,보행자보호의무위반,교차로,교차로횡단보도내,승용,40대,3
...,...,...,...,...,...,...,...,...,...,...,...,...
30033,금호2.3가동,22029,153,0.188954,차대사람,횡단중,보행자보호의무위반,교차로,교차로횡단보도내,승용,60대,3
30037,잠실동,106675,580,0.159044,차대사람,보도통행중,안전운전불이행,기타,기타,자전거,10대 이하,5
30038,상계동,197660,955,0.202115,차대사람,차도통행중,안전운전불이행,교차로,교차로안,승용,60대,5
30042,신림동,234013,3320,0.166093,차대사람,횡단중,보행자보호의무위반,교차로,교차로횡단보도내,화물,70대,6
30045,장안동,71064,597,0.184256,차대사람,횡단중,보행자보호의무위반,교차로,교차로횡단보도내,승용,50대,3

## 차대차

In [112]:
feature2_counts = df2.groupby('행정동')['사고유형 - 소분류'].value_counts().unstack(fill_value=0)
feature2_counts.columns = [f'사고유형 - 소분류_{col}' for col in feature2_counts.columns]

In [113]:
feature3_counts = df2.groupby('행정동')['법규위반'].value_counts().unstack(fill_value=0)
feature3_counts.columns = [f'법규위반_{col}' for col in feature3_counts.columns]

In [114]:
feature4_counts = df2.groupby('행정동')['도로형태 - 대분류'].value_counts().unstack(fill_value=0)
feature4_counts.columns = [f'도로형태 - 대분류_{col}' for col in feature4_counts.columns]

In [115]:
feature5_counts = df2.groupby('행정동')['도로형태 - 소분류'].value_counts().unstack(fill_value=0)
feature5_counts.columns = [f'도로형태 - 소분류_{col}' for col in feature5_counts.columns]

In [116]:
feature6_counts = df2.groupby('행정동')['가해운전자 차종'].value_counts().unstack(fill_value=0)
feature6_counts.columns = [f'가해운전자 차종_{col}' for col in feature6_counts.columns]

In [117]:
feature7_counts = df2.groupby('행정동')['가해운전자 연령대'].value_counts().unstack(fill_value=0)
feature7_counts.columns = [f'가해운전자 연령대_{col}' for col in feature7_counts.columns]

In [118]:
aggregated_df2 = df2.groupby('행정동').sum().reset_index()

In [119]:
aggregated_df2.head()

,행정동,total_population,street parking,senior_ratio,사고유형 - 대분류,사고유형 - 소분류,법규위반,도로형태 - 대분류,도로형태 - 소분류,가해운전자 차종,가해운전자 연령대,ECLO
0,가락동,23512167,515592,43.826635,차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대...,기타 기타 추돌 측면충돌 추돌 추돌 추돌 기타 기타 기타 기타 추돌 기타 측면충돌...,안전운전불이행안전운전불이행안전운전불이행안전운전불이행기타안전운전불이행안전운전불이행안전...,단일로 교차로 단일로 교차로 단일로 단일로 단일로 기타 교차로 단일로 단일로 교차로...,기타 교차로부근 기타 교차로안 기타 기타 기타 기타 교차로안 기타 기타 교차로부근...,이륜승용승용승용승용승용승용화물승용승용승용승용승용승용화물원동기화물화물승용승용승용승합승...,30대50대60대70대20대30대20대60대60대20대40대40대40대60대30대3...,1199
1,가리봉동,901331,3869,13.628007,차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대...,기타 측면충돌 추돌 기타 측면충돌 추돌 기타 측면충돌 측면충돌 추돌 추돌 기타 측...,안전운전불이행안전운전불이행안전운전불이행신호위반안전운전불이행안전거리미확보신호위반신호위...,기타 교차로 교차로 교차로 단일로 단일로 교차로 교차로 교차로 교차로 교차로 교차로...,기타 교차로부근 교차로부근 교차로안 기타 기타 교차로안 교차로안 교차로부근 교차로...,화물승용승용승용승용승용화물승용승합승용승용승용승용승합이륜승용승용승합이륜이륜이륜승용기타...,50대20대30대60대30대70대50대20대60대40대60대40대30대50대60대2...,302
2,가산동,4806900,50575,19.775739,차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대...,측면충돌 기타 측면충돌 측면충돌 측면충돌 기타 정면충돌 측면충돌 기타 기타 추돌 ...,안전운전불이행중앙선침범중앙선침범안전운전불이행신호위반중앙선침범신호위반안전운전불이행안전...,교차로 단일로 단일로 단일로 교차로 기타 교차로 교차로 단일로 단일로 단일로 교차로...,교차로안 기타 기타 기타 교차로안 기타 교차로안 교차로부근 기타 기타 기타 교차로...,화물이륜자전거승용화물승용승용화물승용화물승용승용승용승용승용승용승용화물승용승용승용승용승...,50대50대50대40대60대60대60대60대40대50대70대20대40대60대40대5...,801
3,가양동,2702742,19698,30.744262,차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대...,기타 추돌 측면충돌 추돌 기타 기타 기타 측면충돌 기타 측면충돌 추돌 측면충돌 측...,안전거리미확보안전거리미확보안전운전불이행안전거리미확보안전거리미확보안전운전불이행안전거리...,단일로 기타 교차로 단일로 단일로 단일로 단일로 교차로 기타 단일로 단일로 교차로 ...,기타 기타 교차로안 기타 교량 고가도로위 기타 교차로횡단보도내 기타 기타 교량 교...,승용승용승용승용승용승합승용승용승용승용승용승용승용기타불명승용승용승용승용승용승용화물승용...,40대30대30대40대60대70대50대70대50대60대30대30대60대50대20대2...,440
4,가회동,86658,4378,4.814420,차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대차 차대...,추돌 기타 측면충돌 측면충돌 측면충돌 추돌 추돌 추돌 기타 측면충돌 측면충돌 후진...,안전운전불이행안전거리미확보신호위반직진우회전진행방해차로위반안전운전불이행안전운전불이행안...,교차로 단일로 단일로 교차로 단일로 교차로 단일로 기타 교차로 단일로 교차로 교차로...,교차로부근 기타 기타 교차로안 기타 교차로부근 기타 기타 교차로안 기타 교차로부근...,승용승용승용이륜이륜승용승용승용승용승용승용승용승용승합승용승용승용이륜승용화물자전거화물,20대70대30대20대40대30대10대 이하40대30대50대30대40대20대70대5...,89

In [120]:
df2_counts = df2[['행정동']].drop_duplicates().set_index('행정동')
df2_counts = df2_counts.join(feature2_counts).join(feature3_counts).join(feature4_counts).join(feature5_counts).join(feature6_counts).join(feature7_counts).reset_index()

In [121]:
df2_counts.head()

,행정동,사고유형 - 소분류_ 기타,사고유형 - 소분류_ 정면충돌,사고유형 - 소분류_ 추돌,사고유형 - 소분류_ 측면충돌,사고유형 - 소분류_ 후진중충돌,법규위반_교차로운행방법위반,법규위반_기타,법규위반_보행자보호의무위반,법규위반_불법유턴,...,가해운전자 차종_특수,가해운전자 차종_화물,가해운전자 연령대_10대 이하,가해운전자 연령대_20대,가해운전자 연령대_30대,가해운전자 연령대_40대,가해운전자 연령대_50대,가해운전자 연령대_60대,가해운전자 연령대_70대,가해운전자 연령대_미분류
0,천호동,49,8,30,73,2,11,8,0,2,...,0,11,1,10,29,24,42,35,17,4
1,한남동,73,9,20,52,5,2,4,0,1,...,0,8,2,24,30,25,31,29,18,0
2,신천동,44,2,36,51,0,5,4,0,2,...,0,9,2,14,27,24,24,25,13,4
3,신림동,156,29,75,191,18,47,6,1,2,...,1,39,7,86,84,59,108,81,40,4
4,불광동,25,1,15,19,2,2,1,0,0,...,0,3,1,12,7,8,13,11,10,0

In [122]:
df2_counts['ECLO'] = aggregated_df2['ECLO']

In [123]:
df2_counts.head()

,행정동,사고유형 - 소분류_ 기타,사고유형 - 소분류_ 정면충돌,사고유형 - 소분류_ 추돌,사고유형 - 소분류_ 측면충돌,사고유형 - 소분류_ 후진중충돌,법규위반_교차로운행방법위반,법규위반_기타,법규위반_보행자보호의무위반,법규위반_불법유턴,...,가해운전자 차종_화물,가해운전자 연령대_10대 이하,가해운전자 연령대_20대,가해운전자 연령대_30대,가해운전자 연령대_40대,가해운전자 연령대_50대,가해운전자 연령대_60대,가해운전자 연령대_70대,가해운전자 연령대_미분류,ECLO
0,천호동,49,8,30,73,2,11,8,0,2,...,11,1,10,29,24,42,35,17,4,1199
1,한남동,73,9,20,52,5,2,4,0,1,...,8,2,24,30,25,31,29,18,0,302
2,신천동,44,2,36,51,0,5,4,0,2,...,9,2,14,27,24,24,25,13,4,801
3,신림동,156,29,75,191,18,47,6,1,2,...,39,7,86,84,59,108,81,40,4,440
4,불광동,25,1,15,19,2,2,1,0,0,...,3,1,12,7,8,13,11,10,0,89

In [124]:
count_df2 = df2.groupby('행정동').size().reset_index(name='행정동_개수')

In [125]:
final_df2 = pd.merge(df2_counts, count_df2, on='행정동')

In [126]:
final_df2.head()

,행정동,사고유형 - 소분류_ 기타,사고유형 - 소분류_ 정면충돌,사고유형 - 소분류_ 추돌,사고유형 - 소분류_ 측면충돌,사고유형 - 소분류_ 후진중충돌,법규위반_교차로운행방법위반,법규위반_기타,법규위반_보행자보호의무위반,법규위반_불법유턴,...,가해운전자 연령대_10대 이하,가해운전자 연령대_20대,가해운전자 연령대_30대,가해운전자 연령대_40대,가해운전자 연령대_50대,가해운전자 연령대_60대,가해운전자 연령대_70대,가해운전자 연령대_미분류,ECLO,행정동_개수
0,천호동,49,8,30,73,2,11,8,0,2,...,1,10,29,24,42,35,17,4,1199,162
1,한남동,73,9,20,52,5,2,4,0,1,...,2,24,30,25,31,29,18,0,302,159
2,신천동,44,2,36,51,0,5,4,0,2,...,2,14,27,24,24,25,13,4,801,133
3,신림동,156,29,75,191,18,47,6,1,2,...,7,86,84,59,108,81,40,4,440,469
4,불광동,25,1,15,19,2,2,1,0,0,...,1,12,7,8,13,11,10,0,89,62

In [127]:
final_df2['평균 ECLO'] = final_df2['ECLO'] / final_df2['행정동_개수']

In [128]:
final_df2.head()

,행정동,사고유형 - 소분류_ 기타,사고유형 - 소분류_ 정면충돌,사고유형 - 소분류_ 추돌,사고유형 - 소분류_ 측면충돌,사고유형 - 소분류_ 후진중충돌,법규위반_교차로운행방법위반,법규위반_기타,법규위반_보행자보호의무위반,법규위반_불법유턴,...,가해운전자 연령대_20대,가해운전자 연령대_30대,가해운전자 연령대_40대,가해운전자 연령대_50대,가해운전자 연령대_60대,가해운전자 연령대_70대,가해운전자 연령대_미분류,ECLO,행정동_개수,평균 ECLO
0,천호동,49,8,30,73,2,11,8,0,2,...,10,29,24,42,35,17,4,1199,162,7.401235
1,한남동,73,9,20,52,5,2,4,0,1,...,24,30,25,31,29,18,0,302,159,1.899371
2,신천동,44,2,36,51,0,5,4,0,2,...,14,27,24,24,25,13,4,801,133,6.022556
3,신림동,156,29,75,191,18,47,6,1,2,...,86,84,59,108,81,40,4,440,469,0.938166
4,불광동,25,1,15,19,2,2,1,0,0,...,12,7,8,13,11,10,0,89,62,1.435484

In [129]:
csv_file_path = '2022_final_차대차.csv'
final_df2.to_csv(csv_file_path, index=False, encoding='cp949')

## 차대 사람

In [137]:
feature2_counts = df3.groupby('행정동')['사고유형 - 소분류'].value_counts().unstack(fill_value=0)
feature2_counts.columns = [f'사고유형 - 소분류_{col}' for col in feature2_counts.columns]

feature3_counts = df3.groupby('행정동')['법규위반'].value_counts().unstack(fill_value=0)
feature3_counts.columns = [f'법규위반_{col}' for col in feature3_counts.columns]

feature4_counts = df3.groupby('행정동')['도로형태 - 대분류'].value_counts().unstack(fill_value=0)
feature4_counts.columns = [f'도로형태 - 대분류_{col}' for col in feature4_counts.columns]

feature5_counts = df3.groupby('행정동')['도로형태 - 소분류'].value_counts().unstack(fill_value=0)
feature5_counts.columns = [f'도로형태 - 소분류_{col}' for col in feature5_counts.columns]

feature6_counts = df3.groupby('행정동')['가해운전자 차종'].value_counts().unstack(fill_value=0)
feature6_counts.columns = [f'가해운전자 차종_{col}' for col in feature6_counts.columns]

feature7_counts = df3.groupby('행정동')['가해운전자 연령대'].value_counts().unstack(fill_value=0)
feature7_counts.columns = [f'가해운전자 연령대_{col}' for col in feature7_counts.columns]

aggregated_df3 = df3.groupby('행정동').sum().reset_index()

df3_counts = df3[['행정동']].drop_duplicates().set_index('행정동')
df3_counts = df3_counts.join(feature2_counts).join(feature3_counts).join(feature4_counts).join(feature5_counts).join(feature6_counts).join(feature7_counts).reset_index()


df3_counts['ECLO'] = aggregated_df3['ECLO']

df3_counts.head()

count_df3 = df3.groupby('행정동').size().reset_index(name='행정동_개수')

final_df3 = pd.merge(df3_counts, count_df3, on='행정동')

final_df3.head()

final_df3['평균 ECLO'] = final_df3['ECLO'] / final_df3['행정동_개수']

final_df3.head()

csv_file_path = '2022_final_차대사람.csv'
final_df3.to_csv(csv_file_path, index=False, encoding='cp949')